/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import java.util.Random;
import Model.validations.UserDataValidations;
import exceptions.InvalidCPException;
import exceptions.InvalidEmailException;
import java.awt.Color;
import ficheros.ClassFichero;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author ericlopgue
 */
public class jFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form jFrameMain
     */
    public jFrameMain() throws FileNotFoundException {
        initComponents();
        initConfig();
        ClassFichero.createFile("user_data_tusIniciales.csv");
        jButtonValidate.setEnabled(true);
        jButtondownload.setEnabled(false);
    }

    public void initConfig() {
        setSize(1200, 800);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Centrar la ventana en la pantalla
        setLocationRelativeTo(null);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIntro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldName1 = new javax.swing.JTextField();
        jLabelError = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldName2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldName3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldName4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldName5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabelError1 = new javax.swing.JLabel();
        jLabelError2 = new javax.swing.JLabel();
        jLabelError3 = new javax.swing.JLabel();
        jLabelError4 = new javax.swing.JLabel();
        jLabelError5 = new javax.swing.JLabel();
        jButtondownload = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonValidate = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelConfirm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        jTextFieldName.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldName.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabel2.setText("NIF:");

        jTextFieldName1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldName1ActionPerformed(evt);
            }
        });

        jLabelError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/chill.jpg"))); // NOI18N

        jTextFieldName2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldName2.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldName2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Email:");

        jTextFieldName3.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldName3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Birthdate:");

        jTextFieldName4.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldName4.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldName4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Age:");

        jTextFieldName5.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldName5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldName5ActionPerformed(evt);
            }
        });

        jLabel7.setText("CP");

        jLabelError1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelError1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelError2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelError2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelError3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelError3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelError4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelError4.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelError5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelError5.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtondownload.setBackground(new java.awt.Color(0, 255, 255));
        jButtondownload.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jButtondownload.setForeground(new java.awt.Color(0, 0, 0));
        jButtondownload.setText("CSV");
        jButtondownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondownloadActionPerformed(evt);
            }
        });

        jButtonReset.setBackground(new java.awt.Color(204, 0, 0));
        jButtonReset.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(0, 0, 0));
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonValidate.setBackground(new java.awt.Color(0, 255, 0));
        jButtonValidate.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jButtonValidate.setForeground(new java.awt.Color(0, 0, 0));
        jButtonValidate.setText("Validate");
        jButtonValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidateActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabelTitle.setText("VALIDADOR DATOS USUARIO");

        jLabelConfirm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelConfirm.setForeground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanelIntroLayout = new javax.swing.GroupLayout(jPanelIntro);
        jPanelIntro.setLayout(jPanelIntroLayout);
        jPanelIntroLayout.setHorizontalGroup(
            jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIntroLayout.createSequentialGroup()
                .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIntroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIntroLayout.createSequentialGroup()
                                .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelIntroLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelIntroLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldName1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelIntroLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldName2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelIntroLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldName3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelError2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelError3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelError1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanelIntroLayout.createSequentialGroup()
                                .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelIntroLayout.createSequentialGroup()
                                        .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanelIntroLayout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldName4))
                                            .addGroup(jPanelIntroLayout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldName5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelError5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelError4, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                                    .addGroup(jPanelIntroLayout.createSequentialGroup()
                                        .addGap(143, 143, 143)
                                        .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonValidate)
                                            .addComponent(jButtondownload, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanelIntroLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabelConfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel3))
            .addGroup(jPanelIntroLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 173, Short.MAX_VALUE))
        );
        jPanelIntroLayout.setVerticalGroup(
            jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIntroLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIntroLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelIntroLayout.createSequentialGroup()
                        .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIntroLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelError)))
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldName1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelError1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldName2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelError2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldName3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelError3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelError4)
                            .addComponent(jTextFieldName4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldName5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelError5))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelConfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtondownload, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelIntro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelIntro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldName1ActionPerformed

    private void jButtonValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidateActionPerformed
        // TODO add your handling code here:
        int tenedor = 0;
        String name = jTextFieldName.getText(); //equivalente a scanner (obtener texto de donde se ha metido)
        if (UserDataValidations.CheckName(name) == false) {
            jLabelError.setForeground(Color.red);
            jLabelError.setText("Incorrect name!");
        } else {
            tenedor += 1;
            jLabelError.setForeground(Color.green);
            jLabelError.setText("Correct name!");
        }
        String NIF = jTextFieldName1.getText(); //equivalente a scanner (obtener texto de donde se ha metido)
        if (UserDataValidations.checkId(1, NIF) == false) {
            jLabelError1.setForeground(Color.red);
            jLabelError1.setText("Incorrect NIF!");
        } else {
            jLabelError1.setForeground(Color.green);
            jLabelError1.setText("Correct NIF!");
            tenedor += 1;

        }
        String email = jTextFieldName2.getText(); //equivalente a scanner (obtener texto de donde se ha metido)
        try {
            UserDataValidations.CheckEmail(email);
            jLabelError2.setForeground(Color.red);
            jLabelError2.setText("Incorrect email!");
        } catch (InvalidEmailException e) {
            jLabelError2.setForeground(Color.green);
            jLabelError2.setText("Correct email!");
            tenedor += 1;
        }

        String birthdate = jTextFieldName3.getText(); //equivalente a scanner (obtener texto de donde se ha metido)
        if (UserDataValidations.CheckFormatDate(birthdate) == false) {
            jLabelError3.setForeground(Color.red);
            jLabelError3.setText("Incorrect birthdate!");
        } else {
            jLabelError3.setForeground(Color.green);
            jLabelError3.setText("Correct birthdate!");
            tenedor += 1;
        }
        String age = jTextFieldName4.getText(); //equivalente a scanner (obtener texto de donde se ha metido)
        if (UserDataValidations.calculateAge(age) == -1) {
            jLabelError4.setForeground(Color.green);
            jLabelError4.setText("Correct age!");
            tenedor += 1;
        } else {
            jLabelError4.setForeground(Color.red);
            jLabelError4.setText("Incorrect age!");
        }

        String cp = jTextFieldName5.getText(); //equivalente a scanner (obtener texto de donde se ha metido)
        try {
            UserDataValidations.CheckPostalCode(cp);
            jLabelError5.setForeground(Color.green);
            jLabelError5.setText("Correct Postal Code!");
            tenedor += 1;
        } catch (InvalidCPException e) {
            jLabelError5.setForeground(Color.red);
            jLabelError5.setText("Incorrect Postal Code!");
        }

        if (tenedor == 6) {
            jTextFieldName.setEditable(false);
            jTextFieldName1.setEditable(false);
            jTextFieldName2.setEditable(false);
            jTextFieldName3.setEditable(false);
            jTextFieldName4.setEditable(false);
            jTextFieldName5.setEditable(false);
            jButtonValidate.setEnabled(false);
            jButtondownload.setEnabled(true);

        }
    }//GEN-LAST:event_jButtonValidateActionPerformed

    private void jTextFieldName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldName2ActionPerformed

    private void jTextFieldName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldName3ActionPerformed

    private void jTextFieldName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldName4ActionPerformed

    private void jTextFieldName5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldName5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldName5ActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldName.setText("");
        jTextFieldName1.setText("");
        jTextFieldName2.setText("");
        jTextFieldName3.setText("");
        jTextFieldName4.setText("");
        jTextFieldName5.setText("");
        jLabelError.setText("");
        jLabelError1.setText("");
        jLabelError2.setText("");
        jLabelError3.setText("");
        jLabelError4.setText("");
        jLabelError5.setText("");
        jTextFieldName.setEditable(true);
        jTextFieldName1.setEditable(true);
        jTextFieldName2.setEditable(true);
        jTextFieldName3.setEditable(true);
        jTextFieldName4.setEditable(true);
        jTextFieldName5.setEditable(true);
        int tenedor = 0;
        jButtonValidate.setEnabled(true);
        jButtondownload.setEnabled(false);
        jLabelConfirm.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtondownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondownloadActionPerformed
        // TODO add your handling code here:
        ClassFichero.writeFile("name;nif;mail;fecha_nac;edad;cod_post\n");
        ClassFichero.writeFile(jTextFieldName.getText() + ";" + jTextFieldName1.getText() + ";" + jTextFieldName2.getText() + ";" + jTextFieldName3.getText() + ";" + jTextFieldName4.getText() + ";" + jTextFieldName5.getText() + "\n");
        jLabelConfirm.setText("Usuario registrado correctamente");
        jButtondownload.setEnabled(false);
    }//GEN-LAST:event_jButtondownloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new jFrameMain().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(jFrameMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonValidate;
    private javax.swing.JButton jButtondownload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelConfirm;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelError1;
    private javax.swing.JLabel jLabelError2;
    private javax.swing.JLabel jLabelError3;
    private javax.swing.JLabel jLabelError4;
    private javax.swing.JLabel jLabelError5;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelIntro;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldName1;
    private javax.swing.JTextField jTextFieldName2;
    private javax.swing.JTextField jTextFieldName3;
    private javax.swing.JTextField jTextFieldName4;
    private javax.swing.JTextField jTextFieldName5;
    // End of variables declaration//GEN-END:variables
}
